<?php
/**
 * @file
 * Code for the GSB Resources feature.
 */

include_once 'gsb_resources.features.inc';

require_once dirname(__FILE__) . '/gsb_resources.formatters.inc';

/**
 * Implement hook_resources_type_info().
 *
 * @return array
 */
function gsb_resources_resources_type_info() {
  $resource_types['resource_callout'] = array(
    'label' => t('Callout'),
    'scheme' => 'callout',
    'use generic streamwrapper' => TRUE,
    'handler' => 'ResourcesEntityHandler',
    'icon' => 'callout.png',
    'icon path' => drupal_get_path('module', 'gsb_resources') . '/assets',
  );
  $resource_types['resource_sidebar'] = array(
    'label' => t('Sidebar'),
    'scheme' => 'sidebar',
    'use generic streamwrapper' => TRUE,
    'handler' => 'ResourcesEntityHandler',
    'icon' => 'sidebar.png',
    'icon path' => drupal_get_path('module', 'gsb_resources') . '/assets',
  );
  $resource_types['resource_soundcloud'] = array(
    'label' => t('SoundCloud'),
    'scheme' => 'soundcloud',
    'use generic streamwrapper' => TRUE,
    'handler' => 'ResourcesSoundCloudHandler',
    'icon' => 'soundcloud.png',
    'icon path' => drupal_get_path('module', 'gsb_resources') . '/assets',
  );
  $resource_types['resource_infogram'] = array(
    'label' => t('Infogram'),
    'scheme' => 'infogram',
    'use generic streamwrapper' => TRUE,
    'handler' => 'ResourcesInfogramHandler',
    'icon' => 'infogram.png',
    'icon path' => drupal_get_path('module', 'gsb_resources') . '/assets',
  );
  $resource_types['resource_art19'] = array(
    'label' => t('Art19'),
    'scheme' => 'art19',
    'use generic streamwrapper' => TRUE,
    'handler' => 'ResourcesArt19Handler',
    'icon' => 'art19.png',
    'icon path' => drupal_get_path('module', 'gsb_resources') . '/assets',
  );
  return $resource_types;
}

/**
 * Implement hook_resources_type_info_alter().
 *
 * @return array
 */
function gsb_resources_resources_type_info_alter(&$resource_types) {
  $resource_types['resource_twitter']['icon'] = 'twitter.png';
  $resource_types['resource_twitter']['icon path'] = drupal_get_path('module', 'gsb_resources') . '/assets';
}

